### PR TITLE
laravel 10 done

### PR DESCRIPTION
**Pull request by CodersFaruk**

### CODE REVIEW

**Review by unicodeveloper — APPROVED** [review]

**Review by twentyFourDesign — APPROVED** [review]
pr looks good to merge

**Comment by twentyFourDesign** [comment]
@unicodeveloper  I am using your packages and waiting for this pr to be merged and new release  for this  to upgrade my laravel version and can't move to next step until this fix is done

**Comment by twentyFourDesign** [comment]
@unicodeveloper  can you prioritize this fix please

**Comment by jayantisuthar** [comment]
@unicodeveloper  Can you merge this pr, I am also looking for this fix ASAP and am stuck in the middle of upgrading my client Laravel project and on the edge of the deadline so please do  merge this fix asap.

**Comment by unicodeveloper** [comment]
@twentyFourDesign @jayantisuthar tagged https://github.com/unicodeveloper/laravel-paystack/releases/tag/1.1.0

**Pull request merged**
