### PR TITLE
added support for multiple currencies

### PR DESCRIPTION
**Pull request by django101**
Hi. Wale from Paystack.

We've had a couple of issues where developes pass the USD currency but still get NGN on the checkout. This is a quick update for that. If there's anywhere else this needs to be fixed, please fix as soon as possible.

### CODE REVIEW

**Comment by benedictgeek** [comment]
> Hi. Wale from Paystack.
> 
> We've had a couple of issues where developes pass the USD currency but still get NGN on the checkout. This is a quick update for that. If there's anywhere else this needs to be fixed, please fix as soon as possible.

Hello, since NGN charges are done in kobo, how do I configure for USD for example, pass the raw USD charge?

**Comment by ladaposamuel** [comment]
Please kindly merge @unicodeveloper

**Comment by django101** [comment]
> > Hi. Wale from Paystack.
> > We've had a couple of issues where developes pass the USD currency but still get NGN on the checkout. This is a quick update for that. If there's anywhere else this needs to be fixed, please fix as soon as possible.
> 
> Hello, since NGN charges are done in kobo, how do I configure for USD for example, pass the raw USD charge?

@benedictgeek Sorry i'm just seeing this.....the same say you pass kobo values for NGN, do the same for USD. So, NGN10.00 = 1000kobo, while USD10.00 = 1000cents

**Comment by unicodeveloper** [comment]
Thank you. Support now added.

**Pull request closed without merging**
